pipeline {
	agent none
	
	tools {
		maven 'Maven'
		jdk 'JDK'
	}

		
	environment {
		JOB_NAME = "acg-cdx-membership-proxy"
		ARTIFACTORY_PATH = "libs-release-local/com/acg/services/api"
		DEPLOYMENT_FOLDER_BUILDNUMBER = "/opt/app/jenkins/jobs/${JOB_NAME}/workspace/Artifact/com/acg/services/api/${JOB_NAME}/${JOB_NAME}-1.0.0-${BUILD_NUMBER}"
		DEPLOYMENT_FOLDER_ARTIFACTVERSION = "/opt/app/jenkins/jobs/${JOB_NAME}/workspace/Artifact/com/acg/services/api/${JOB_NAME}/${JOB_NAME}-1.0.0-${ArtifactVersion}"
		GITHUB_CREDS = credentials('github-thiagopri')
	}

	stages{
		stage('Build and Test') {
			agent any
			steps {
				sh 'echo skip'
				//sh 'mvn -f ${JOB_NAME}/pom.xml -B -U -e -V clean package'
			}
		}
		
		stage('Update pom version') {
			agent any
			steps {
				//sh 'mvn -f ${JOB_NAME}/pom.xml build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit'
				//sh 'mvn -f ${JOB_NAME}/pom.xml build-helper:parse-version versions:set -DnewVersion=\\${parsedVersion.majorVersion}.\\${parsedVersion.minorVersion}.${BUILD_NUMBER} versions:commit'
				//GIT PAT = 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
				//Jenkins Token = 118220010a15ac785170400f182995f508
				sh 'git config user.name "Build Agent"'
				sh 'git config user.email "cicd_agent@acg.aaa.com"'
				sh 'git config credential.helper "!f() { sleep 1; echo \"username=${env.GITHUB_CREDS_USR}\"; echo \"password=${env.GITHUB_CREDS_PSW}\"; }; f"'
				//sh 'git checkout -q ${GIT_BRANCH}'
				sh 'git checkout -q $(echo "${GIT_BRANCH}" | sed "s@.*/@@")'
				sh 'git pull -q'
				sh 'mvn -f ${JOB_NAME}/pom.xml build-helper:parse-version versions:set -DnewVersion=\\${parsedVersion.majorVersion}.\\${parsedVersion.minorVersion}.\\${parsedVersion.nextIncrementalVersion} versions:commit'
				sh 'git commit -q -a -m "Asset version bumped ***NO_CI***"'
				//withCredentials([gitUsernamePassword(credentialsId: 'github-thiagopri', gitToolName: 'Default')]) {
				sh 'git push -q'
				//}

			}
		}

		//dev Deployment
		stage('Deploy to Anypoint Exchange'){
			agent any
			steps {
				sh 'echo skip'
				//sh 'mvn -f ${JOB_NAME}/pom.xml -s settings.xml -U -V -e -B deploy -DskipTests'
			}	
		}

		//dev Deployment
		stage('Dev Deploy'){
			agent any
			
			steps {
				sh 'echo skip'
				//sh 'mvn -f ${JOB_NAME}/pom.xml -s settings.xml -U -V -e -B deploy -DskipTests -DmuleDeploy -Dapp.name=acg-cdx-membershipproxy-rfapi-dev-v1 -Drtf.target=acg-rtf-dev -Denv="dev" -Danypoint.username="acgapiplatform" -Danypoint.password="AcgMulesoft@100" -Drtf.environment="DEV" -Danypoint.platform.client_id="087b2709f4ca42a7a49e1b2983bcbf31" -Danypoint.platform.client_secret="B4515383fBd142228B65cafABaDd90f0"'
			}	
		}

		stage ("Approval to deploy to QA") {
			agent none
			steps {
                emailext (
					subject: "Deploy to QA - Approval Pending",
					body: """<p>There is a <b>QA</b> deployment pending for your approval: Job '${JOB_NAME} - ${BUILD_NUMBER}':</p>
					<p>Access the follow URL and approve/reject this deploument: <a href='${BUILD_URL}/input'>Approve/Reject</a></p>""",
					to: "thiagopri@gmail.com",
					from: "thiago@moveisconforto.com.br"
                ) 		

				timeout(time: 12, unit: 'HOURS') {
					input 'Do you want to proceed to the Deployment?'
				}
			}
		}



		//Deploy Prod Notification
		stage('Deploy QA'){
			agent any
			steps {
				sh 'echo skip'
				//sh 'mvn -f ${JOB_NAME}/pom.xml -s settings.xml -U -V -e -B deploy -DskipTests -DmuleDeploy -Dapp.name=acg-cdx-membershipproxy-rfapi-qa-v1 -Drtf.target=acg-rtf-test -Denv="dev" -Danypoint.username="acgapiplatform" -Danypoint.password="AcgMulesoft@100" -Drtf.environment="QA" -Danypoint.platform.client_id="087b2709f4ca42a7a49e1b2983bcbf31" -Danypoint.platform.client_secret="B4515383fBd142228B65cafABaDd90f0"'
			}	
		}
	}



	post{
		
		always{
			agent any
			cleanWs()
		}
		aborted{
			agent any
			cleanWs()
		}
		failure{
			agent any
			cleanWs()
		}
		success{
			agent any
			cleanWs()
		}
	}


	


}
