
/*
Pipeline script for 
Version 1.01
*/


import java.text.SimpleDateFormat
import java.time.*
import java.time.format.DateTimeFormatter

def deployables = ""

pipeline {
	agent any
	
	tools {
    maven 'Maven'
    jdk 'JDK'
}
	
environment {
	ARTIFACTORY_PATH = "libs-release-local/com/acg/services/api"
	DEPLOYMENT_FOLDER_BUILDNUMBER = "/opt/app/jenkins/jobs/${JOB_NAME}/workspace/Artifact/com/acg/services/api/${JOB_NAME}/${JOB_NAME}-1.0.0-${BUILD_NUMBER}"
	DEPLOYMENT_FOLDER_ARTIFACTVERSION = "/opt/app/jenkins/jobs/${JOB_NAME}/workspace/Artifact/com/acg/services/api/${JOB_NAME}/${JOB_NAME}-1.0.0-${ArtifactVersion}"
}

stages{
	stage('Build and Test') {
		steps {
			sh 'mvn -f ${JOB_NAME}/pom.xml -B -U -e -V clean package'
		}
	}
	

	//dev Deployment
	stage('Deploy to Anypoint Exchange'){
		steps {
			sh 'mvn -f ${JOB_NAME}/pom.xml -s settings.xml -U -V -e -B deploy -DskipTests'
		}	
	}

	//dev Deployment
	stage('Dev Deploy'){
		steps {
			sh 'mvn -f ${JOB_NAME}/pom.xml -s settings.xml -U -V -e -B deploy -DskipTests -DmuleDeploy -Dapp.name=acg-cdx-membershipproxy-rfapi-dev-v1 -Denv="dev" -Danypoint.username="acgapiplatform" -Danypoint.password="AcgMulesoft@100" -Drtf.environment="DEV" -Danypoint.platform.client_id="087b2709f4ca42a7a49e1b2983bcbf31" -Danypoint.platform.client_secret="B4515383fBd142228B65cafABaDd90f0"'
		}	
	}
}

post{
	always{
		cleanWs()
	}
	aborted{
		cleanWs()
	}
	failure{
		cleanWs()
	}
	success{
		cleanWs()
	}
}


	


}
