{
    "RETURN_CD": "0",
    "MBR_ID": "12347588",
    "ASSOC_MBR_ID": "1",
    "MBR_ID_16": "4299941234758818",
    "MBR_SLTN_CD": null,
    "MBR_LST_NM": "JONES",
    "MBR_MID_INIT_NM": null,
    "MBR_FST_NM": "CHLOE",
    "MBR_NM_GEN_CD": null,
    "MBR_NM_SUFX_CD": null,
    "MBR_BSC_AD": "112 Maple Lane",
    "MBR_SUPL_AD": null,
    "MBR_ADR_CTY_NM": "Riverside",
    "MBR_ADR_ST_PROV_CD": "NY",
    "MBR_ADR_PSTL_CD": "01004",
    "MBR_ADR_CNTRY_CD": null,
    "MBR_TEL_NR": "2234571803",
    "MBR_TEL_EXT_NR": null,
    "MBR_SUPL_TEL_NR": null,
    "MBR_JN_AAA_YR_DT": null,
    "MBRS_STS_CD": "P",
    "MBRS_PLS_IN": "P",
    "MBRS_ERS_ABS_IN": "N",
    "MBRS_RTN_CHK_IN": "N",
    "MBRS_MOTORCYCLE_IN": "Y",
    "MBRS_EXPIR_DT": "20251231",
    "MBRS_PAID_THRU_DT": "20211231",
    "MBRS_UPDATED_TM": "2021-09-15 05:36:06 EDT",
    "MBRS_NOTE_TX": "Plus=Y #Asc=3YrJn="
}