{
    "MembershipSearchResponse": {
        "MEMBER": [
            {
                "MBR_ID": "63795483",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290146379548300",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "ANNIE",
                "MBR_BSC_AD": "PO BOX 433",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "69813858",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290146981385802",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "ANNIE",
                "MBR_BSC_AD": "2245 2ND ST",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "65313442",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290146531344200",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "BARBARA",
                "MBR_BSC_AD": "4653 HAMMOCK RIDGE DR",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "68582251",
                "ASSOC_MBR_ID": "1",
                "MBR_ID_16": "4290146858225115",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "BRIAN",
                "MBR_BSC_AD": "267 CESARA ESTATES LOOP",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "C"
            },
            {
                "MBR_ID": "17758963",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290141775896304",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "CAROL",
                "MBR_BSC_AD": "3364 DIAMOND TER",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "C"
            },
            {
                "MBR_ID": "18272046",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290141827204606",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "DALLAS",
                "MBR_BSC_AD": "2944 BLACKWATER OAKS DR",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "65712330",
                "ASSOC_MBR_ID": "1",
                "MBR_ID_16": "4290146571233016",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "DELROY",
                "MBR_BSC_AD": "4055 WILLOW DR",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "65133137",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290146513313702",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "DONOVAN",
                "MBR_BSC_AD": "5325 NORRIS LAKE CT",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "13724574",
                "ASSOC_MBR_ID": "1",
                "MBR_ID_16": "4290141372457419",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "JANIE",
                "MBR_BSC_AD": "3803 OPAL DR",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            },
            {
                "MBR_ID": "68666631",
                "ASSOC_MBR_ID": null,
                "MBR_ID_16": "4290146866663109",
                "MBR_LST_NM": "JONES",
                "MBR_FST_NM": "KEITH",
                "MBR_BSC_AD": "4055 WILLOW DR",
                "MBR_SUPL_AD": null,
                "MBR_ADR_CTY_NM": "MULBERRY",
                "MBR_ADR_ST_PROV_CD": "FL",
                "MBR_ADR_PSTL_CD": "33860",
                "MBRS_STS_CD": "A"
            }
        ]
    }
}